on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.14'
      add-prefix:
        type: string
        default: ''
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # For OIDC token exchange with Qlty:
      # - Configuring OpenID Connect in cloud providers - GitHub Docs
      #   https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-cloud-providers#adding-permissions-settings
      id-token: write
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ inputs.python-version }}
      - run: uv sync
      - run: uv run invoke test.coverage --xml
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage.xml
          format: cobertura
          add-prefix: ${{ inputs.add-prefix }}
